version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    # Solución alternativa: ejecuta el comando a través de un shell
    command: ["sh", "-c", "celery -A app.core.celery.celery_app worker --loglevel=info"]

volumes:
  redis-data: