from typing import Optional

from sqlalchemy import Column, DECIMAL, DateTime, Index, Integer, PrimaryKeyConstraint, String, Table
from sqlalchemy.dialects.mssql import TINYINT
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
import datetime
import decimal

class Base(DeclarativeBase):
    pass

class SPartes(Base):
    __tablename__ = 'SPartes'
    __table_args__ = (
        PrimaryKeyConstraint('NUMPARTE', name='Partes_PKNumParte'),
    )

    NUMPARTE: Mapped[str] = mapped_column(String(70, 'Modern_Spanish_CI_AS'), primary_key=True)
    TIPOPARTE: Mapped[Optional[str]] = mapped_column(String(10, 'Modern_Spanish_CI_AS'))
    NUMPARTECOM: Mapped[Optional[str]] = mapped_column(String(70, 'Modern_Spanish_CI_AS'))
    NUMPARTEREF: Mapped[Optional[str]] = mapped_column(String(70, 'Modern_Spanish_CI_AS'))
    DESCRIPCIONE: Mapped[Optional[str]] = mapped_column(String(500, 'Modern_Spanish_CI_AS'))
    DESCRIPCIONI: Mapped[Optional[str]] = mapped_column(String(500, 'Modern_Spanish_CI_AS'))
    CLASE: Mapped[Optional[str]] = mapped_column(String(8, 'Modern_Spanish_CI_AS'))
    UNIMED: Mapped[Optional[str]] = mapped_column(String(5, 'Modern_Spanish_CI_AS'))
    UNIMEDEQUIV: Mapped[Optional[str]] = mapped_column(String(5, 'Modern_Spanish_CI_AS'))
    FACTORCONV: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    COSTOUNITARIO: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    TIPOMONEDA: Mapped[Optional[str]] = mapped_column(String(2, 'Modern_Spanish_CI_AS'))
    CLAVEMONEDA: Mapped[Optional[str]] = mapped_column(String(3, 'Modern_Spanish_CI_AS'))
    PESOUNITARIO: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    TIPOMAT: Mapped[Optional[str]] = mapped_column(String(10, 'Modern_Spanish_CI_AS'))
    FRACCION: Mapped[Optional[str]] = mapped_column(String(10, 'Modern_Spanish_CI_AS'))
    FRACCIONAME: Mapped[Optional[str]] = mapped_column(String(16, 'Modern_Spanish_CI_AS'))
    ADVALOREMAME: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(5, 2))
    FRACCAMEEXPONDUTY: Mapped[Optional[str]] = mapped_column(String(16, 'Modern_Spanish_CI_AS'))
    FRACEUA: Mapped[Optional[str]] = mapped_column(String(13, 'Modern_Spanish_CI_AS'))
    FRACCANADA: Mapped[Optional[str]] = mapped_column(String(13, 'Modern_Spanish_CI_AS'))
    SUBEMPRESA: Mapped[Optional[str]] = mapped_column(String(5, 'Modern_Spanish_CI_AS'))
    UMEXISTENCIA: Mapped[Optional[str]] = mapped_column(String(5, 'Modern_Spanish_CI_AS'))
    VALORAGREGADO: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    TIPOVA: Mapped[Optional[str]] = mapped_column(String(2, 'Modern_Spanish_CI_AS'))
    FECHAMODIFICA: Mapped[Optional[int]] = mapped_column(Integer)
    UNIMEDALTERNA: Mapped[Optional[str]] = mapped_column(String(5, 'Modern_Spanish_CI_AS'))
    CLAVEFDA: Mapped[Optional[str]] = mapped_column(String(20, 'Modern_Spanish_CI_AS'))
    LEYENDASEG: Mapped[Optional[str]] = mapped_column(String(1500, 'Modern_Spanish_CI_AS'))
    VALORNOORIG: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    IMPPAGAR: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    DESCESPSCRAP: Mapped[Optional[str]] = mapped_column(String(499, 'Modern_Spanish_CI_AS'))
    DESCINGSCRAP: Mapped[Optional[str]] = mapped_column(String(499, 'Modern_Spanish_CI_AS'))
    FRACEXPOSCRAP: Mapped[Optional[str]] = mapped_column(String(10, 'Modern_Spanish_CI_AS'))
    FRACAMESCRAP: Mapped[Optional[str]] = mapped_column(String(16, 'Modern_Spanish_CI_AS'))
    FECHACOSTO: Mapped[Optional[int]] = mapped_column(Integer)
    FOTOPARTE: Mapped[Optional[str]] = mapped_column(String(255, 'Modern_Spanish_CI_AS'))
    CAPXUMAUXILIAR: Mapped[Optional[str]] = mapped_column(String(1, 'Modern_Spanish_CI_AS'))
    FACTORAUXILIAR: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(13, 6))
    UMAUXILIAR: Mapped[Optional[str]] = mapped_column(String(5, 'Modern_Spanish_CI_AS'))
    COSTOUAUXILIAR: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    CAPTXKILO: Mapped[Optional[str]] = mapped_column(String(1, 'Modern_Spanish_CI_AS'))
    CANTKILO: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    COSTOVENTA: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    CANTPZXCJ: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(15, 0))
    VERSIONBILL: Mapped[Optional[int]] = mapped_column(Integer)
    NUMPARTESUS: Mapped[Optional[str]] = mapped_column(String(70, 'Modern_Spanish_CI_AS'))
    ESREPARACION: Mapped[Optional[str]] = mapped_column(String(3, 'Modern_Spanish_CI_AS'))
    COSTOUNITARIOREP: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    USACANTALTERNA: Mapped[Optional[int]] = mapped_column(TINYINT)
    FECHAMODBOM: Mapped[Optional[int]] = mapped_column(Integer)
    FECHAMODFRACAME: Mapped[Optional[int]] = mapped_column(Integer)
    VALORAGREGADOREP: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    ESMATPELIGROSO: Mapped[Optional[str]] = mapped_column(String(1, 'Modern_Spanish_CI_AS'))
    NUMEMERGENCIA: Mapped[Optional[str]] = mapped_column(String(30, 'Modern_Spanish_CI_AS'))
    CLASEDEPELIGRO: Mapped[Optional[str]] = mapped_column(String(4, 'Modern_Spanish_CI_AS'))
    NUMIDENTIFICACIONUN: Mapped[Optional[str]] = mapped_column(String(6, 'Modern_Spanish_CI_AS'))
    GRUPOEMBALAJE: Mapped[Optional[str]] = mapped_column(String(3, 'Modern_Spanish_CI_AS'))
    NOMAPROPIADOEMB: Mapped[Optional[str]] = mapped_column(String(500, 'Modern_Spanish_CI_AS'))
    NOTASMATPELIGROSO: Mapped[Optional[str]] = mapped_column(String(499, 'Modern_Spanish_CI_AS'))
    VALORDUTY: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    FLETEDUTY: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALORTOTALDUTY: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALORNODUTY: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    FLETENODUTY: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALORTOTALNDUTY: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALORTOTAL: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    TRABAJODIREC: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    GASTOGRALES: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    OTROSGASTOS: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    TOTALGASTOS: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    DEPRECIACION: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    TOOLING: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    MATCONSUMED: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALORSCRAP: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    FORENGDESDEV: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALTOTALASIST: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALEMPAQUEFOR: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    GANANCIA: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    DUTIABLEVALUE7: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    OTROSNDUTIABLE: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    COSTOESTIMADO: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    TOTALNDUTIABLE: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    ACTUALDUTIABLE: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALEMPAQUEUS: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    VALEMPAQUENAC: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(23, 8))
    FECHACOSTOAME: Mapped[Optional[int]] = mapped_column(Integer)
    ESTEXTIL: Mapped[Optional[str]] = mapped_column(String(2, 'Modern_Spanish_CI_AS'))
    PROVEEDOR: Mapped[Optional[str]] = mapped_column(String(8, 'Modern_Spanish_CI_AS'))
    ECCN: Mapped[Optional[str]] = mapped_column(String(20, 'Modern_Spanish_CI_AS'))
    SIMBOLOEXCLIC: Mapped[Optional[str]] = mapped_column(String(19, 'Modern_Spanish_CI_AS'))
    CAMPOOPCIONAL: Mapped[Optional[str]] = mapped_column(String(800, 'Modern_Spanish_CI_AS'))
    UNIMEDEQUIV2: Mapped[Optional[str]] = mapped_column(String(5, 'Modern_Spanish_CI_AS'))
    FACTORCONV2: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    LABORCOST: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    EXPORTCODE: Mapped[Optional[str]] = mapped_column(String(2, 'Modern_Spanish_CI_AS'))
    LICENSECODE: Mapped[Optional[str]] = mapped_column(String(3, 'Modern_Spanish_CI_AS'))
    CAMPOOPCIONALBOM: Mapped[Optional[str]] = mapped_column(String(200, 'Modern_Spanish_CI_AS'))
    TIPOPESO: Mapped[Optional[str]] = mapped_column(String(6, 'Modern_Spanish_CI_AS'))
    TIPOIMMEX: Mapped[Optional[str]] = mapped_column(String(20, 'Modern_Spanish_CI_AS'))
    CLAVEFCC: Mapped[Optional[str]] = mapped_column(String(30, 'Modern_Spanish_CI_AS'))
    NUMPARTESCRAP: Mapped[Optional[str]] = mapped_column(String(70, 'Modern_Spanish_CI_AS'))
    NUMPARTEMERMA: Mapped[Optional[str]] = mapped_column(String(70, 'Modern_Spanish_CI_AS'))
    FACTORDESP: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    HABILITADADESHABILITADA: Mapped[Optional[int]] = mapped_column(TINYINT)
    FECHAMODIFICA_ISO: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    VERSIONBOM: Mapped[Optional[int]] = mapped_column(Integer)
    ORDENVENTA: Mapped[Optional[str]] = mapped_column(String(50, 'Modern_Spanish_CI_AS'))
    CLIENTEASIGNADO: Mapped[Optional[str]] = mapped_column(String(50, 'Modern_Spanish_CI_AS'))
    ANCHURA: Mapped[Optional[str]] = mapped_column(String(50, 'Modern_Spanish_CI_AS'))
    ESPESOR: Mapped[Optional[str]] = mapped_column(String(50, 'Modern_Spanish_CI_AS'))
    SPEC: Mapped[Optional[str]] = mapped_column(String(50, 'Modern_Spanish_CI_AS'))
    FACTORCONVERSION: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(19, 8))
    UMCONVERSION: Mapped[Optional[str]] = mapped_column(String(9, 'Modern_Spanish_CI_AS'))
    NOTIFICARSIPARTEUSAREGLA8VA: Mapped[Optional[int]] = mapped_column(Integer)
    FECHACREACIONPARTE: Mapped[Optional[int]] = mapped_column(Integer)
    LLENARINFOSUGERIDAR8: Mapped[Optional[int]] = mapped_column(Integer)
    RESULTADOCALCULONAFTA: Mapped[Optional[str]] = mapped_column(String(19, 'Modern_Spanish_CI_AS'))
    PORCENTAJECALCULONAFTA: Mapped[Optional[decimal.Decimal]] = mapped_column(DECIMAL(5, 2))
    MDI: Mapped[Optional[str]] = mapped_column(String(25, 'Modern_Spanish_CI_AS'))
    CONSECUTIVOATF: Mapped[Optional[int]] = mapped_column(Integer)
    FRACCIONAMERICANASIFRA: Mapped[Optional[str]] = mapped_column(String(19, 'Modern_Spanish_CI_AS'))
    NUMPARTEREFFLEX: Mapped[Optional[str]] = mapped_column(String(120, 'Modern_Spanish_CI_AS'))
    DTA: Mapped[Optional[str]] = mapped_column(String(19, 'Modern_Spanish_CI_AS'))
    DTB: Mapped[Optional[str]] = mapped_column(String(19, 'Modern_Spanish_CI_AS'))
    DTG: Mapped[Optional[str]] = mapped_column(String(19, 'Modern_Spanish_CI_AS'))
    IDENTIFICADOR: Mapped[Optional[str]] = mapped_column(String(1000, 'Modern_Spanish_CI_AS'))
    CONSECUTIVOAPHIS: Mapped[Optional[int]] = mapped_column(Integer)

t_SPartesClientes = Table(
    'SPartesClientes', Base.metadata,
    Column('NUMPARTE', String(70, 'Modern_Spanish_CI_AS')),
    Column('CLIENTE', String(8, 'Modern_Spanish_CI_AS')),
    Column('NOMBREPARTECLIENTE', String(200, 'Modern_Spanish_CI_AS')),
    Index('PARCLI_ParteCliente', 'NUMPARTE', 'CLIENTE', unique=True)
)